plenta_jobs_basic.offer_filter:
    path: /_plenta-jobs-basic/offer/filter
    defaults:
        _scope: frontend
        _token_check: false
        _controller: Plenta\ContaoJobsBasic\Controller\JobsOfferFilterRequestController::filterOffersAction

Plenta\ContaoJobsBasic\Controller\Contao\BackendModule\SettingsController:
    path: /%contao.backend.route_prefix%/plentajobsbasic/settings
    defaults:
        _scope: backend
        _controller: Plenta\ContaoJobsBasic\Controller\Contao\BackendModule\SettingsController::showSettings

jobs_basic:
    resource: ../src/Controller
    type: attribute
